/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
	id("com.google.devtools.ksp") version "2.2.0-2.0.2"
	kotlin("jvm") version "2.2.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }
	mavenCentral()
}

dependencies {
    api(libs.org.json.json)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    api(libs.org.jetbrains.kotlin.kotlin.reflect)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core)
	implementation(kotlin("compiler-embeddable"))
    compileOnly(libs.io.papermc.paper.paper.api)
	ksp(project(":processor"))
	implementation("com.google.devtools.ksp:symbol-processing-api:2.2.0-2.0.2")
	implementation(kotlin("stdlib-jdk8"))
}

group = "vip.qoriginal"
version = "1.14.5.5.1"
description = "QuantumPlugin"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
kotlin {
	jvmToolchain(21)
}