/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
	base
	`maven-publish`
	id("com.google.devtools.ksp") version "2.3.9" apply false
	kotlin("jvm") version "2.3.21" apply false
	id("com.gradleup.shadow") version "9.4.2" apply false
	id("io.papermc.paperweight.userdev") version "2.0.0-SNAPSHOT" apply false
}

val qpluginVersion = "1.14.5.5.1"

allprojects {
	group = "vip.qoriginal"
	version = qpluginVersion
	description = "QuantumPlugin"

	repositories {
		mavenLocal()
		maven {
			url = uri("https://repo.maven.apache.org/maven2/")
		}
		maven {
			url = uri("https://repo.papermc.io/repository/maven-public/")
		}
		maven {
			url = uri("https://oss.sonatype.org/content/groups/public/")
		}
		mavenCentral()
	}
}

val javaProjects = listOf(project(":common"), project(":survival"), project(":creative"))
val jsonDependency = libs.org.json.json
val kotlinStdlibDependency = libs.org.jetbrains.kotlin.kotlin.stdlib
val kotlinReflectDependency = libs.org.jetbrains.kotlin.kotlin.reflect
val coroutinesDependency = libs.org.jetbrains.kotlinx.kotlinx.coroutines.core
val paperApiDependency = libs.io.papermc.paper.paper.api

configure(javaProjects) {
	apply(plugin = "java-library")
	apply(plugin = "org.jetbrains.kotlin.jvm")
	apply(plugin = "maven-publish")

	dependencies {
		"api"(jsonDependency)
		"api"(kotlinStdlibDependency)
		"api"(kotlinReflectDependency)
		"api"(coroutinesDependency)
		"compileOnly"(paperApiDependency)
		"implementation"(kotlin("stdlib-jdk8"))
	}

	tasks.withType<JavaCompile>().configureEach {
		options.encoding = "UTF-8"
	}

	tasks.withType<Javadoc>().configureEach {
		options.encoding = "UTF-8"
	}

	extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension>("kotlin") {
		jvmToolchain(21)
		sourceSets.named("main") {
			kotlin.setSrcDirs(listOf("src/main/java"))
		}
	}

	publishing {
		publications.create<MavenPublication>("maven") {
			from(components["java"])
		}
	}
}

val pluginProjects = mapOf(
	"survival" to "QuantumPlugin",
	"creative" to "QuantumPlugin-Creative",
)

pluginProjects.forEach { (projectName, archiveName) ->
	project(":$projectName") {
		apply(plugin = "com.gradleup.shadow")

		dependencies {
		"implementation"(project(":common"))
		"implementation"(kotlin("compiler-embeddable"))
		"implementation"("com.google.devtools.ksp:symbol-processing-api:2.3.9")
	}

		tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
			archiveBaseName.set(archiveName)
			archiveClassifier.set("")
			mergeServiceFiles()
			dependencies {
				exclude(dependency("com.google.devtools.ksp:.*"))
				exclude(dependency("org.jetbrains.kotlin:kotlin-compiler-embeddable.*"))
			}
		}

		tasks.named("build") {
			dependsOn("shadowJar")
		}
	}
}

project(":survival") {
	apply(plugin = "com.google.devtools.ksp")
	apply(plugin = "io.papermc.paperweight.userdev")

	extensions.configure<org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension>("kotlin") {
		jvmToolchain(25)
	}

	val survivalJavaToolchains = extensions.getByType<org.gradle.jvm.toolchain.JavaToolchainService>()
	extensions.configure<io.papermc.paperweight.userdev.PaperweightUserExtension>("paperweight") {
		javaLauncher.set(survivalJavaToolchains.launcherFor {
			languageVersion.set(JavaLanguageVersion.of(25))
		})
		reobfArtifactConfiguration.set(io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION)
	}

	dependencies {
		"ksp"(project(":processor"))
		"implementation"("io.github.classgraph:classgraph:4.8.181")
		"paperweightDevelopmentBundle"("io.papermc.paper:dev-bundle:26.1.2.build.+")
	}
}

tasks.named("build") {
	dependsOn(":survival:shadowJar", ":creative:shadowJar")
}
