pluginManagement {
	plugins {
		kotlin("jvm") version "2.2.0"
	}
}
include(":processor")

plugins {
	id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "QuantumPlugin"
