pluginManagement {
	repositories {
		gradlePluginPortal()
		maven("https://repo.papermc.io/repository/maven-public/")
	}
	plugins {
		kotlin("jvm") version "2.3.21"
	}
}
include(":common")
include(":survival")
include(":creative")
include(":processor")

plugins {
	id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "QuantumPlugin"
